# Generated by Django 5.0.6 on 2026-05-21 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('final_url', models.URLField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_score', models.SmallIntegerField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=512)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True, help_text='Executive summary from GPT-4o.')),
                ('ai_suggestions', models.JSONField(blank=True, default=dict, help_text='Structured AI output: suggested_title, suggested_meta_description, top_recommendations, content_quality_score, content_verdict.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SEO Check',
                'verbose_name_plural': 'SEO Checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='seo_checker_status_732f15_idx'), models.Index(fields=['celery_task_id'], name='seo_checker_celery__c4e805_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('display_name', models.CharField(max_length=80)),
                ('score', models.SmallIntegerField()),
                ('checks_data', models.JSONField(default=list, help_text='Serialised list of Check dataclass instances.')),
                ('seo_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='seo_checker.seocheck')),
            ],
            options={
                'verbose_name': 'Check Category',
                'verbose_name_plural': 'Check Categories',
                'ordering': ['category'],
                'unique_together': {('seo_check', 'category')},
            },
        ),
    ]
